# coding: utf-8

"""
    universal search engine

    universal search engine api  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import universal_search_engine
from universal_search_engine.models.object import Object  # noqa: E501
from universal_search_engine.rest import ApiException


class TestObject(unittest.TestCase):
    """Object unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObject(self):
        """Test Object"""
        # FIXME: construct object with mandatory attributes with example values
        # model = universal_search_engine.models.object.Object()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
