# coding: utf-8

"""
    universal search engine

    universal search engine api  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Object(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'obejct_id': 'str'
    }

    attribute_map = {
        'obejct_id': 'obejctID'
    }

    def __init__(self, obejct_id=None):  # noqa: E501
        """Object - a model defined in Swagger"""  # noqa: E501

        self._obejct_id = None
        self.discriminator = None

        if obejct_id is not None:
            self.obejct_id = obejct_id

    @property
    def obejct_id(self):
        """Gets the obejct_id of this Object.  # noqa: E501

        This will be unique in every object in index  # noqa: E501

        :return: The obejct_id of this Object.  # noqa: E501
        :rtype: str
        """
        return self._obejct_id

    @obejct_id.setter
    def obejct_id(self, obejct_id):
        """Sets the obejct_id of this Object.

        This will be unique in every object in index  # noqa: E501

        :param obejct_id: The obejct_id of this Object.  # noqa: E501
        :type: str
        """

        self._obejct_id = obejct_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Object, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Object):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
