# coding: utf-8

"""
    universal search engine

    universal search engine api  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SearchParameters(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pre_filter': 'str',
        'post_filters': 'object'
    }

    attribute_map = {
        'pre_filter': 'preFilter',
        'post_filters': 'postFilters'
    }

    def __init__(self, pre_filter=None, post_filters=None):  # noqa: E501
        """SearchParameters - a model defined in Swagger"""  # noqa: E501

        self._pre_filter = None
        self._post_filters = None
        self.discriminator = None

        if pre_filter is not None:
            self.pre_filter = pre_filter
        if post_filters is not None:
            self.post_filters = post_filters

    @property
    def pre_filter(self):
        """Gets the pre_filter of this SearchParameters.  # noqa: E501


        :return: The pre_filter of this SearchParameters.  # noqa: E501
        :rtype: str
        """
        return self._pre_filter

    @pre_filter.setter
    def pre_filter(self, pre_filter):
        """Sets the pre_filter of this SearchParameters.


        :param pre_filter: The pre_filter of this SearchParameters.  # noqa: E501
        :type: str
        """

        self._pre_filter = pre_filter

    @property
    def post_filters(self):
        """Gets the post_filters of this SearchParameters.  # noqa: E501

        a dictionary of key, value where key is category name, and value is array of accepted filters  # noqa: E501

        :return: The post_filters of this SearchParameters.  # noqa: E501
        :rtype: object
        """
        return self._post_filters

    @post_filters.setter
    def post_filters(self, post_filters):
        """Sets the post_filters of this SearchParameters.

        a dictionary of key, value where key is category name, and value is array of accepted filters  # noqa: E501

        :param post_filters: The post_filters of this SearchParameters.  # noqa: E501
        :type: object
        """

        self._post_filters = post_filters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SearchParameters, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SearchParameters):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
